import { defineConfig } from 'vite';
import path from 'node:path';
import { animStudioSavePlugin } from './src/save-plugin';
import { animStudioProjectPlugin } from './src/project-plugin';

// Must byte-match the header of demo/clips.ts so a Save never reformats it.
const DEMO_BANNER = `// GENERATED by anim-studio (demo). Do not hand-edit — author in the studio
// (npm run dev), Save, and commit to seal an animation.
//
// bodyId → clip id → keyframe timeline. With no entry a body renders its
// procedural default byte-for-byte.`;

export default defineConfig({
  base: './',
  plugins: [
    // The demo keeps its own statically-configured save endpoint, so every
    // existing embedded host keeps working exactly as it did in v0.2.
    animStudioSavePlugin({
      root: __dirname,
      file: 'demo/clips.ts',
      banner: DEMO_BANNER,
      typesImport: `import type { BodyClips, MotionOverride } from '../src/types';`,
      skeletonsFile: 'demo/skeletons.json',
    }),
    // The standalone host: `/` edits whichever project the header selects.
    animStudioProjectPlugin({ root: __dirname, configFile: 'anim-studio.config.json' }),
  ],
  server: {
    host: '0.0.0.0',
    port: 5199,
  },
  build: {
    outDir: 'dist',
    target: 'es2022',
    rollupOptions: {
      input: {
        studio: path.resolve(__dirname, 'index.html'),
        demo: path.resolve(__dirname, 'demo/index.html'),
      },
    },
  },
});
