import { defineConfig } from 'vite';
import path from 'node:path';
import { animStudioSavePlugin } from './src/save-plugin';

// Must byte-match the header of demo/clips.ts so a Save never reformats it.
const DEMO_BANNER = `// GENERATED by anim-studio (demo). Do not hand-edit — author in the studio
// (npm run dev), Save, and commit to seal an animation.
//
// bodyId → clip id → keyframe timeline. With no entry a body renders its
// procedural default byte-for-byte.`;

export default defineConfig({
  base: './',
  plugins: [
    animStudioSavePlugin({
      root: __dirname,
      file: 'demo/clips.ts',
      banner: DEMO_BANNER,
      typesImport: `import type { BodyClips, MotionOverride } from '../src/types';`,
      skeletonsFile: 'demo/skeletons.json',
    }),
  ],
  server: {
    host: '0.0.0.0',
    port: 5199,
    open: '/demo/',
  },
  build: {
    outDir: 'dist',
    target: 'es2022',
    rollupOptions: {
      input: path.resolve(__dirname, 'demo/index.html'),
    },
  },
});
