/**
 * The extraction-parity bridge — proves the standalone anim-studio package is
 * a FAITHFUL generalization of this game's animation data channel, against
 * the game's real data:
 *
 *  1. the package sampler and the game sampler (src/data/anim/sample.ts)
 *     agree on every timeline in the shipped ANIM_CLIPS — on keys, between
 *     keys, at boundaries;
 *  2. the package emitter writes BYTE-IDENTICALLY what the game's own Save
 *     endpoint (tools/animeditor/save-plugin.ts) writes for the real parsed
 *     baseline — a Save through the generic plugin lands the same file;
 *  3. round-tripping src/data/anim/clips.ts through the package emitter
 *     never changes the DATA and is a fixed point. (Byte order of the file
 *     itself isn't canonical today: tools/anim-author/apply.mjs appends its
 *     authored keys unsorted, so the first Save canonicalizes key order once
 *     — same data, sorted keys.)
 *
 * Runs in the repo's vitest (`npm test`). The package's own node:test suite
 * covers its behavior in isolation; this file covers the seam to the game.
 */
import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import { ANIM_CLIPS } from '@/data/anim/clips';
import { samplePose as gameSample } from '@/data/anim/sample';
import { emitClips as gameEmit } from '../../animeditor/save-plugin';
import { samplePose as pkgSample } from '../src/sample';
import { emitClipsModule } from '../src/emit';
import type { ClipTimeline } from '../src/types';

/** The exact banner the game's Save endpoint writes (save-plugin.ts). */
const GAME_SAVE_BANNER = `// GENERATED by the Animation Studio (tools/animeditor). Do not hand-edit —
// re-authored via the studio's Save and committed to git to seal an animation.
//
// bodyId → clip id → keyframe timeline. With no entry a body renders its
// procedural default byte-for-byte (see src/data/anim/types.ts).`;

const CLIPS_FILE = new URL('../../../src/data/anim/clips.ts', import.meta.url).pathname;

describe('anim-studio extraction parity', () => {
  it('package sampler matches the game sampler across the whole shipped baseline', () => {
    let samples = 0;
    const mismatches: string[] = [];
    for (const [bodyId, bc] of Object.entries(ANIM_CLIPS)) {
      for (const [clip, tl] of Object.entries(bc)) {
        const ts = new Set<number>([0, 0.1, 1 / 3, 0.5, 0.77, 1]);
        const keys = (tl as ClipTimeline).keys;
        for (const k of keys) ts.add(k.t);
        for (let i = 0; i < keys.length - 1; i++) ts.add((keys[i].t + keys[i + 1].t) / 2);
        for (const t of ts) {
          samples++;
          const a = JSON.stringify(pkgSample(tl as ClipTimeline, t) ?? null);
          const b = JSON.stringify(gameSample(tl, t) ?? null);
          if (a !== b && mismatches.length < 5) mismatches.push(`${bodyId}/${clip}@${t}: ${a} != ${b}`);
        }
      }
    }
    expect(mismatches).toEqual([]);
    // the baseline is the whole cast — make sure we actually swept it
    expect(Object.keys(ANIM_CLIPS).length).toBeGreaterThan(100);
    expect(samples).toBeGreaterThan(10000);
  });

  it('package emitter writes byte-identically what the game Save endpoint writes', () => {
    const file = fs.readFileSync(CLIPS_FILE, 'utf8');
    const lit = file.match(/^export const ANIM_CLIPS: Record<string, BodyClips> = (.*);$/m);
    expect(lit).toBeTruthy();
    const parsed = JSON.parse(lit![1]) as Record<string, unknown>;
    const emitted = emitClipsModule(parsed, {
      banner: GAME_SAVE_BANNER,
      typesImport: `import type { BodyClips, MotionOverride } from './types';`,
    });
    expect(emitted).toBe(gameEmit(parsed));
  });

  it('round-tripping the shipped clips.ts is data-lossless and a fixed point', () => {
    const file = fs.readFileSync(CLIPS_FILE, 'utf8');
    const importIdx = file.indexOf('\nimport type');
    expect(importIdx).toBeGreaterThan(0);
    const banner = file.slice(0, importIdx);
    const lit = file.match(/^export const ANIM_CLIPS: Record<string, BodyClips> = (.*);$/m);
    const parsed = JSON.parse(lit![1]) as Record<string, unknown>;
    const opts = { banner, typesImport: `import type { BodyClips, MotionOverride } from './types';` };
    const once = emitClipsModule(parsed, opts);
    // same data (order-insensitive)…
    const relit = once.match(/^export const ANIM_CLIPS: Record<string, BodyClips> = (.*);$/m);
    expect(JSON.parse(relit![1])).toEqual(parsed);
    // …and canonical: emitting again is byte-stable
    expect(emitClipsModule(JSON.parse(relit![1]), opts)).toBe(once);
  });
});
