/**
 * Headless end-to-end verify for the studio: boots the demo in Chromium,
 * drives the __ae hook through the WHOLE authoring loop — view a body, pose a
 * bone, keyframe, Save to demo/clips.ts, reload, and prove the authored edit
 * replays through the bake path (the baked frame actually changes) — then
 * restores the clips file. Non-destructive.
 *
 *   npm run verify              # spawns its own vite dev server
 *
 * Set CHROMIUM_PATH to a chrome binary to skip Playwright's managed download.
 */
import { chromium } from 'playwright';
import fs from 'node:fs';

const PKG = new URL('..', import.meta.url).pathname;
const CLIPS = PKG + 'demo/clips.ts';
const SHOT = new URL('./verify-shot.png', import.meta.url).pathname;

const snapshot = fs.readFileSync(CLIPS, 'utf8');
const { createServer } = await import('vite');
const server = await createServer({
  configFile: PKG + 'vite.config.ts',
  root: PKG,
  server: { port: 0, open: false },
});
await server.listen();
const port = server.httpServer.address().port;

const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || undefined });
const page = await browser.newPage({ viewport: { width: 1280, height: 760 } });
const errors = [];
const notFound = [];
page.on('console', (m) => { if (m.type() === 'error' && !/Failed to load resource/.test(m.text())) errors.push(m.text()); });
page.on('pageerror', (e) => errors.push('PAGEERROR: ' + e.message));
page.on('response', (r) => { if (r.status() === 404) notFound.push(new URL(r.url()).pathname); });

const fail = (msg) => {
  console.error('✗ ' + msg);
  process.exitCode = 1;
};

try {
  await page.goto(`http://localhost:${port}/demo/`, { waitUntil: 'load' });
  await page.waitForFunction(() => window.__ae && window.__ae.ready(), null, { timeout: 20000 });

  const out = {};
  out.count = await page.evaluate(() => window.__ae.count());
  out.labels = await page.evaluate(() => window.__ae.labels());
  if (out.count < 3 || !out.labels.includes('scout') || !out.labels.includes('wisp')) fail(`roster wrong: ${JSON.stringify(out.labels)}`);

  // --- the view path: clips + a non-empty preview ---------------------------
  out.clips = await page.evaluate(() => window.__ae.clips());
  if (!out.clips.includes('attack') || !out.clips.includes('idle')) fail(`scout clips wrong: ${out.clips}`);
  const gotoFrame = (clipName, frame) =>
    page.evaluate(([c, f]) => {
      window.__ae.setClip(window.__ae.clips().indexOf(c));
      const scrub = document.querySelector('[data-as="scrub"]');
      scrub.value = String(f);
      scrub.dispatchEvent(new Event('input'));
    }, [clipName, frame]);
  await gotoFrame('attack', 3);
  const png = () => page.evaluate(() => document.querySelector('[data-as="preview"]').toDataURL());
  const pixels = await page.evaluate(() => {
    const c = document.querySelector('[data-as="preview"]');
    const d = c.getContext('2d').getImageData(0, 0, c.width, c.height).data;
    let n = 0;
    for (let i = 3; i < d.length; i += 4) if (d[i] > 10) n++;
    return n;
  });
  if (pixels < 50) fail(`preview near-empty (${pixels}px)`);
  const beforeEdit = await png();

  // --- a view-only body has no rig ------------------------------------------
  await page.evaluate((i) => window.__ae.select(i), out.labels.indexOf('wisp'));
  await page.waitForFunction(() => window.__ae.state().name === 'wisp');
  out.wisp = await page.evaluate(() => window.__ae.state());
  if (out.wisp.poseable) fail('wisp should be view-only');

  // --- the authoring loop: pose → key → save ---------------------------------
  await page.evaluate((i) => window.__ae.select(i), out.labels.indexOf('scout'));
  await page.waitForFunction(() => window.__ae.state().name === 'scout');
  await gotoFrame('attack', 3);
  await page.evaluate(() => window.__ae.setPose(true));
  out.bones = await page.evaluate(() => window.__ae.bones());
  const kinds = new Set(out.bones.map((b) => b.kind));
  if (!(kinds.has('arm') && kinds.has('leg') && kinds.has('root'))) fail(`bones missing kinds: ${JSON.stringify(out.bones)}`);
  await page.evaluate(() => window.__ae.nudge('arm1', 0.7));
  out.keys = await page.evaluate(() => window.__ae.authoredKeys());
  if (out.keys < 1) fail('nudge did not author a key');
  out.saved = await page.evaluate(() => window.__ae.save());
  if (!out.saved) fail('save endpoint failed');
  const written = fs.readFileSync(CLIPS, 'utf8');
  if (!written.includes('"scout:staff"') || !written.includes('"arm1"')) fail('clips.ts missing the authored key');
  if (!written.startsWith('// GENERATED by anim-studio (demo).')) fail('clips.ts banner not preserved');

  // --- the replay: reload → the authored key changes the BAKED frame --------
  await page.reload({ waitUntil: 'load' });
  await page.waitForFunction(() => window.__ae && window.__ae.ready(), null, { timeout: 20000 });
  const keysAfterReload = await page.evaluate(() => window.__ae.authoredKeys());
  if (keysAfterReload < 1) fail('authored store did not load from the saved file');
  await gotoFrame('attack', 3);
  const afterEdit = await png();
  if (afterEdit === beforeEdit) fail('authored key did not change the baked frame after reload');
  // …and only where authored: an unkeyed frame elsewhere is untouched by design
  await page.screenshot({ path: SHOT });

  out.errors = errors;
  out.notFound = notFound.filter((p) => p !== '/favicon.ico'); // favicon 404 is benign
  if (errors.length) fail(`console errors: ${errors.join(' | ')}`);
  if (out.notFound.length) fail(`404s: ${out.notFound.join(' ')}`);
  console.log(JSON.stringify({ ...out, bones: out.bones.length }, null, 2));
  if (process.exitCode !== 1) console.log('✓ studio verify passed');
} finally {
  fs.writeFileSync(CLIPS, snapshot); // non-destructive: restore the demo data
  await browser.close();
  await server.close();
}
