// GENERATED by anim-studio (demo). Do not hand-edit — author in the studio
// (npm run dev), Save, and commit to seal an animation.
//
// bodyId → clip id → keyframe timeline. With no entry a body renders its
// procedural default byte-for-byte.
import type { BodyClips, MotionOverride } from '../src/types';

export const ANIM_CLIPS: Record<string, BodyClips> = {};

export const ANIM_OVERRIDES: Record<string, MotionOverride> = {};
