/**
 * Emit the authored clip store as a file — either plain JSON or a typed
 * TypeScript module. Deterministic on purpose:
 *  - object keys are deep-sorted → stable, small git diffs;
 *  - numbers keep FULL precision (a converted baseline stores the exact floats
 *    the procedural rig computed, and its replay is byte-identical only
 *    because they round-trip exactly — never quantise here);
 *  - only negative zero is normalised (JSON turns -0 into 0 anyway; do it
 *    explicitly so the emitted file is stable);
 *  - the JSON literal is compact (one line), so a studio save never reformats
 *    a large baseline into a pretty-printed 100k-line diff.
 */

const norm = (n: number): number => (Object.is(n, -0) ? 0 : n);

/** Deep-sort object keys and normalise -0 → a canonical, diff-stable value. */
export function stableClips(v: unknown): unknown {
  if (Array.isArray(v)) return v.map(stableClips);
  if (v && typeof v === 'object') {
    const out: Record<string, unknown> = {};
    for (const k of Object.keys(v as Record<string, unknown>).sort()) out[k] = stableClips((v as Record<string, unknown>)[k]);
    return out;
  }
  return typeof v === 'number' ? norm(v) : v;
}

/** The canonical compact JSON body for a clip store. */
export function clipsLiteral(clips: unknown): string {
  return JSON.stringify(stableClips(clips ?? {}), null, 0);
}

/** Emit the store as a plain JSON file (trailing newline included). */
export function emitClipsJson(clips: unknown): string {
  return clipsLiteral(clips) + '\n';
}

export interface EmitModuleOptions {
  /** Full comment header (each line already `//`-prefixed), without a trailing
   *  newline. Defaults to a generic studio banner. */
  banner?: string;
  /** The `import type` line for the exported consts' types. Defaults to
   *  importing {@link BodyClips}/{@link MotionOverride} from `./types` —
   *  point it wherever your copy of the format types lives. */
  typesImport?: string;
  /** Name of the exported clip-store const. */
  clipsExport?: string;
  /** Name of the exported motion-override const; `false` omits it. */
  overridesExport?: string | false;
}

const DEFAULT_BANNER = `// GENERATED by anim-studio. Do not hand-edit — re-authored via the studio's
// Save and committed to git to seal an animation.
//
// bodyId → clip id → keyframe timeline. With no entry a body renders its
// procedural default byte-for-byte.`;

/** Emit the store as a typed TypeScript module — the same shape a game imports
 *  at bake time. Byte-stable for a given store + options. */
export function emitClipsModule(clips: unknown, opts: EmitModuleOptions = {}): string {
  const banner = opts.banner ?? DEFAULT_BANNER;
  const typesImport = opts.typesImport ?? `import type { BodyClips, MotionOverride } from './types';`;
  const clipsExport = opts.clipsExport ?? 'ANIM_CLIPS';
  const overridesExport = opts.overridesExport ?? 'ANIM_OVERRIDES';
  const lit = clipsLiteral(clips);
  let out = `${banner}\n${typesImport}\n\nexport const ${clipsExport}: Record<string, BodyClips> = ${lit};\n`;
  if (overridesExport) out += `\nexport const ${overridesExport}: Record<string, MotionOverride> = {};\n`;
  return out;
}
